title: Extending ImageJ Macro auto completion
logo: /images/haesleinhuepf.jpg
description: A Tutorial
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
